# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-rootelegram

# >> macros
# << macros
%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude ^libtdjson.*$
%define _binary_payload w6.xzdio

Summary:    RooTelegram is a Telegram client for Sailfish OS
Version:    1.1
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://werkwolf.eu/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-rootelegram.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   nemo-qml-plugin-contacts-qt5
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5Positioning)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  gperf
BuildRequires:  desktop-file-utils

%description
RooTelegram is a Telegram client for Sailfish OS


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# rlottie: crea directory e config.h vuoto (il submodule è già stato inizializzato)
mkdir -p rlottie/src/vector
touch rlottie/src/vector/config.h
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop
%posttrans
# Ensure daemon/UI restart on install/upgrade so new binaries are picked up without reboot
/usr/bin/pkill -TERM -f '(/|^)%{name}([[:space:]]|$)' >/dev/null 2>&1 || :
/usr/bin/pkill -TERM -f '(/|^)rootelegram([[:space:]]|$)' >/dev/null 2>&1 || :
/usr/bin/sleep 1
/usr/bin/pkill -KILL -f '(/|^)%{name}([[:space:]]|$)' >/dev/null 2>&1 || :
/usr/bin/pkill -KILL -f '(/|^)rootelegram([[:space:]]|$)' >/dev/null 2>&1 || :

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
