# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-rootelegram

# >> macros
# << macros
%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude ^libtdjson.*$
%define _binary_payload w6.xzdio

Summary:    RooTelegram is a Telegram client for Sailfish OS
Version:    1.5
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://werkwolf.eu/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-rootelegram.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   nemo-qml-plugin-contacts-qt5
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Sql)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5Positioning)
BuildRequires:  pkgconfig(nemonotifications-qt5)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  gperf
BuildRequires:  desktop-file-utils

%description
RooTelegram is a Telegram client for Sailfish OS


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# rlottie: crea directory e config.h vuoto (il submodule è già stato inizializzato)
mkdir -p rlottie/src/vector
touch rlottie/src/vector/config.h
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%pre
# Clean-slate preinstall: kill any running RooTelegram processes and wipe ALL
# RooTelegram-related state under every user's home so the new version starts
# with no stale config, no stale TDLib session, no stale D-Bus .service files.
# Required because the application identifier changed from de.ygriega to
# com.github.RootGPT_YouTube between RooTelegram 1.2 and 1.3, and the various
# leftover D-Bus / cache / lipstick references would otherwise prevent the
# launcher from activating the new bus name reliably. The user must log in
# again to Telegram (OTP) after the upgrade — this is by design.
#
# Match the binary path /usr/bin/harbour-rootelegram (present in the cmdline
# of the binary itself, the invoker wrapper, and the firejail wrapper).
# Do NOT match on the bare "harbour-rootelegram" string — it would also match
# the parent `rpm -Uvh .../harbour-rootelegram-*.rpm` and kill the transaction
# (and the user's shell).
KILL_PATTERN='/usr/bin/harbour-rootelegram'
pkill -f "$KILL_PATTERN" >/dev/null 2>&1 || true
i=0
while pgrep -f "$KILL_PATTERN" >/dev/null 2>&1 && [ $i -lt 10 ]; do
    sleep 0.2
    i=$((i+1))
done
pkill -9 -f "$KILL_PATTERN" >/dev/null 2>&1 || true

for user_home in /home/*/; do
    [ -d "$user_home" ] || continue
    owner_user=$(stat -c '%U' "$user_home" 2>/dev/null) || continue
    [ "$owner_user" != "root" ] || continue

    # Only perform the destructive wipe when we still see legacy `de.ygriega`
    # state on disk: that signals a real 1.2 → 1.3 migration where the bus
    # name and sandbox identifier changed, and a clean slate is required for
    # lipstick / sailjail to pick up the new identity. Once the legacy paths
    # are gone, subsequent installs of 1.3+ are pure upgrades and MUST keep
    # the user's Telegram session intact.
    legacy_present=false
    if [ -d "${user_home}.config/de.ygriega" ] || \
       [ -d "${user_home}.local/share/de.ygriega" ] || \
       [ -d "${user_home}.cache/de.ygriega" ]; then
        legacy_present=true
    fi
    [ "$legacy_present" = true ] || continue

    # Drop a marker file so %posttrans knows it must restart lipstick to
    # invalidate the cached legacy D-Bus bus name. Without this marker, every
    # plain 1.3+ upgrade would needlessly restart Home (~10s black screen).
    : > /var/tmp/rootelegram-legacy-migration

    # Wipe every RooTelegram-related state directory for this user, under both
    # the legacy (de.ygriega) and the current (com.github.RootGPT_YouTube)
    # application identifiers.
    rm -rf \
        "${user_home}.config/de.ygriega" \
        "${user_home}.local/share/de.ygriega" \
        "${user_home}.cache/de.ygriega" \
        "${user_home}.config/com.github.RootGPT_YouTube" \
        "${user_home}.local/share/com.github.RootGPT_YouTube" \
        "${user_home}.cache/com.github.RootGPT_YouTube"

    # Remove every D-Bus .service file referencing RooTelegram under either
    # identifier, in both the persistent location and the runtime location
    # (`/run/user/<uid>/dbus-1/services/` is regenerated by sailjail at next
    # activation).
    rm -f "${user_home}.local/share/dbus-1/services/de.ygriega.rootelegram.service" \
          "${user_home}.local/share/dbus-1/services/com.github.RootGPT_YouTube.rootelegram.service"
    owner_uid=$(id -u "$owner_user" 2>/dev/null) || continue
    [ -n "$owner_uid" ] && rm -f \
        "/run/user/${owner_uid}/dbus-1/services/de.ygriega.rootelegram.service" \
        "/run/user/${owner_uid}/dbus-1/services/com.github.RootGPT_YouTube.rootelegram.service"
done

exit 0

%posttrans
# Restart each user's lipstick (Sailfish Home) ONLY if %pre detected a real
# 1.2 → 1.3 migration (marker file present). Without this gate, every plain
# 1.3+ reinstall would force a ~10s Home reload for nothing. On a legacy
# migration we still need the restart so the launcher drops its cached
# mapping to the old de.ygriega D-Bus name (otherwise the icon tap fails
# with "Remote action failed: The name de.ygriega.rootelegram was not
# provided by any .service files").
MARKER=/var/tmp/rootelegram-legacy-migration
if [ ! -f "$MARKER" ]; then
    exit 0
fi
rm -f "$MARKER"

for user_home in /home/*/; do
    [ -d "$user_home" ] || continue
    user=$(stat -c '%U' "$user_home" 2>/dev/null) || continue
    [ "$user" = "root" ] && continue
    uid=$(id -u "$user" 2>/dev/null) || continue
    [ -n "$uid" ] || continue
    [ -d "/run/user/$uid" ] || continue
    # Only restart if lipstick is actually running in this user's session.
    if runuser -u "$user" -- env XDG_RUNTIME_DIR="/run/user/$uid" \
            systemctl --user is-active --quiet lipstick 2>/dev/null; then
        runuser -u "$user" -- env XDG_RUNTIME_DIR="/run/user/$uid" \
            systemctl --user restart lipstick >/dev/null 2>&1 || true
    fi
done

exit 0

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
